export { Link } from '@/components/link'
export { Footer } from '@/components/footer'
export { Meta } from '@/components/meta'
export { Header } from '@/components/header'
export { Layout } from '@/components/layout'
export { Hero } from '@/components/hero'
export { About } from '@/components/about'
export { HowItWorks } from '@/components/how-it-works'

export { CodeBlock } from '@/components/code-block'
